import { PREFIX_CONST_REQUEST, PREFIX_NAME } from './base';

export const ON_CHANGE_OPEN_KEYS = `${PREFIX_NAME}_ON_CHANGE_OPEN_KEYS`;

export const APP = {
  ...PREFIX_CONST_REQUEST('ROUTER'),
  ...PREFIX_CONST_REQUEST('SYSTEM_CONFIG'),
};

export const LOGIN = {
  ...PREFIX_CONST_REQUEST('LOGOUT'),
  ...PREFIX_CONST_REQUEST('REFRESH'),
  ...PREFIX_CONST_REQUEST('SUBMITING'),
};

export const APPPOST = {
  ...PREFIX_CONST_REQUEST('APP_POST_DETAIL'),
  ...PREFIX_CONST_REQUEST('APP_POST_SEARCH'),
  ...PREFIX_CONST_REQUEST('APP_POST_FETCHING'),
};

export const ADMINPOST = {
  ...PREFIX_CONST_REQUEST('ADMIN_POST_SEARCH'),
  ...PREFIX_CONST_REQUEST('ADMIN_POST_CREATE'),
  ...PREFIX_CONST_REQUEST('ADMIN_POST_UPDATE'),
  ...PREFIX_CONST_REQUEST('ADMIN_POST_DELETE'),
};

export const ADMINCATEGORY = {
  ...PREFIX_CONST_REQUEST('ADMIN_CATEGORY_SEARCH'),
  ...PREFIX_CONST_REQUEST('ADMIN_CATEGORY_CREATE'),
  ...PREFIX_CONST_REQUEST('ADMIN_CATEGORY_UPDATE'),
  ...PREFIX_CONST_REQUEST('ADMIN_CATEGORY_DELETE'),
};
